<?php


namespace app\controllers;


use Exception;
use yii\filters\ContentNegotiator;
use yii\helpers\Json;
use yii\rest\Controller;
use yii\web\Response;

class RestController extends Controller
{

    public const STATUS_SUCCESS = 0,
        STATUS_ERROR = 1,
        STATUS_SERVER_ERROR = -1;

    /**
     * @return array
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors(); // TODO: Change the autogenerated stub
        $behaviors['contentNegotiator'] = [
            'class' => ContentNegotiator::class,
            'formats' => [
                'application/json' => Response::FORMAT_JSON,
            ],
        ];
        unset($behaviors['authenticator']);
        return $behaviors;
    }


    public function runAction($id, $params = [])
    {
        try {
            return parent::runAction($id, $params);
        } catch (Throwable $exception) {
            return new Response(['data' => Json::encode($this->serializeData($exception))]);
        }
    }

    protected function serializeData($data)
    {
        $response = [];
        $response['status'] = self::STATUS_SUCCESS;

        if ($data instanceof Exception || $data instanceof \TypeError) {
            $response['status'] = self::STATUS_ERROR;
            if (defined('YII_ENV_DEV')) {
                $response['message'] = $data->getMessage();
            } else {
                $response['message'] = 'ERROR_SYSTEM_GENERAL';
            }
            return $response;

        }

        $data = parent::serializeData($data);

        $response['data'] = $data;

        return $response;
    }


}